# Generated by Django 3.1.7 on 2021-03-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Property', 'Property'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture'), ('Bikes', 'Bikes'), ('Cars', 'Cars'), ('Books&Sports', 'Books&Sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('UK', 'Uttarakhand'), ('JH', 'Jharkhand'), ('TS', 'Telegana'), ('BR', 'Bihar'), ('AS', 'Assam'), ('KL', 'Kerala'), ('ML', 'Meghalaya'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('MI', 'Sikkim'), ('HP', 'Haryana'), ('TR', 'Tripura'), ('MZ', 'Mizoram'), ('GJ', 'Gujarat'), ('KA', 'Karnataka'), ('WB', 'West Bengal'), ('NL', 'Nagaland'), ('MN', 'Manipur'), ('OD', 'Odisha'), ('RJ', 'Rajasthan'), ('PB', 'Punjab'), ('UP', 'Uttar Pradesh'), ('GA', 'Goa'), ('AP', 'Andhra Pradesh'), ('CG', 'Chhattisgarh'), ('AR', 'Arunachal Pradesh'), ('MP', 'Madhya Pradesh')], max_length=100),
        ),
    ]
