# Generated by Django 2.0 on 2021-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210313_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Bikes', 'Bikes'), ('Furniture', 'Furniture'), ('Property', 'Property'), ('Mobiles', 'Mobiles'), ('Cars', 'Cars'), ('Electronics', 'Electronics'), ('Jobs', 'Jobs'), ('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MZ', 'Mizoram'), ('MH', 'Maharashtra'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('KL', 'Kerala'), ('NL', 'Nagaland'), ('HP', 'Haryana'), ('GA', 'Goa'), ('TN', 'Tamil Nadu'), ('AP', 'Andhra Pradesh'), ('JH', 'Jharkhand'), ('AS', 'Assam'), ('BR', 'Bihar'), ('GJ', 'Gujarat'), ('WB', 'West Bengal'), ('ML', 'Meghalaya'), ('OD', 'Odisha'), ('MN', 'Manipur'), ('RJ', 'Rajasthan'), ('MP', 'Madhya Pradesh'), ('KA', 'Karnataka'), ('CG', 'Chhattisgarh'), ('PB', 'Punjab'), ('AR', 'Arunachal Pradesh'), ('TR', 'Tripura'), ('TS', 'Telegana'), ('MI', 'Sikkim')], max_length=100),
        ),
    ]
