# Generated by Django 2.0 on 2021-03-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210313_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Mobiles', 'Mobiles'), ('Books&Sports', 'Books&Sports'), ('Furniture', 'Furniture'), ('Laptops', 'Laptops'), ('Property', 'Property'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('TR', 'Tripura'), ('KL', 'Kerala'), ('MH', 'Maharashtra'), ('UK', 'Uttarakhand'), ('KA', 'Karnataka'), ('UP', 'Uttar Pradesh'), ('RJ', 'Rajasthan'), ('BR', 'Bihar'), ('TS', 'Telegana'), ('ML', 'Meghalaya'), ('TN', 'Tamil Nadu'), ('MZ', 'Mizoram'), ('MI', 'Sikkim'), ('MN', 'Manipur'), ('WB', 'West Bengal'), ('CG', 'Chhattisgarh'), ('ND', 'New Delhi'), ('OD', 'Odisha'), ('HP', 'Haryana'), ('NL', 'Nagaland'), ('AS', 'Assam'), ('MP', 'Madhya Pradesh'), ('AR', 'Arunachal Pradesh'), ('AP', 'Andhra Pradesh'), ('PB', 'Punjab'), ('GA', 'Goa'), ('JH', 'Jharkhand'), ('GJ', 'Gujarat')], max_length=100),
        ),
    ]
