# Generated by Django 2.0 on 2021-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210313_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Bikes', 'Bikes'), ('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Books&Sports', 'Books&Sports'), ('Property', 'Property'), ('Laptops', 'Laptops'), ('Cars', 'Cars'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('HP', 'Haryana'), ('NL', 'Nagaland'), ('TS', 'Telegana'), ('BR', 'Bihar'), ('GA', 'Goa'), ('RJ', 'Rajasthan'), ('TN', 'Tamil Nadu'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('CG', 'Chhattisgarh'), ('KA', 'Karnataka'), ('AS', 'Assam'), ('MI', 'Sikkim'), ('UP', 'Uttar Pradesh'), ('AR', 'Arunachal Pradesh'), ('KL', 'Kerala'), ('MZ', 'Mizoram'), ('ND', 'New Delhi'), ('MN', 'Manipur'), ('GJ', 'Gujarat'), ('OD', 'Odisha'), ('ML', 'Meghalaya'), ('JH', 'Jharkhand'), ('WB', 'West Bengal'), ('AP', 'Andhra Pradesh'), ('PB', 'Punjab'), ('TR', 'Tripura'), ('UK', 'Uttarakhand')], max_length=100),
        ),
    ]
