# Generated by Django 2.0 on 2021-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210318_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books&Sports', 'Books&Sports'), ('Bikes', 'Bikes'), ('Laptops', 'Laptops'), ('Jobs', 'Jobs'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles'), ('Property', 'Property'), ('Cars', 'Cars'), ('Furniture', 'Furniture'), ('Fashion', 'Fashion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('ML', 'Meghalaya'), ('HP', 'Haryana'), ('KL', 'Kerala'), ('GA', 'Goa'), ('TN', 'Tamil Nadu'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('MZ', 'Mizoram'), ('ND', 'New Delhi'), ('PB', 'Punjab'), ('GJ', 'Gujarat'), ('UP', 'Uttar Pradesh'), ('AS', 'Assam'), ('AP', 'Andhra Pradesh'), ('UK', 'Uttarakhand'), ('RJ', 'Rajasthan'), ('MH', 'Maharashtra'), ('WB', 'West Bengal'), ('TR', 'Tripura'), ('TS', 'Telegana'), ('MI', 'Sikkim'), ('MN', 'Manipur'), ('AR', 'Arunachal Pradesh'), ('BR', 'Bihar'), ('OD', 'Odisha'), ('NL', 'Nagaland'), ('CG', 'Chhattisgarh'), ('MP', 'Madhya Pradesh')], max_length=100),
        ),
    ]
