# Generated by Django 2.0 on 2021-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210318_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Bikes', 'Bikes'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Laptops', 'Laptops'), ('Property', 'Property'), ('Mobiles', 'Mobiles'), ('Cars', 'Cars'), ('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('GA', 'Goa'), ('TR', 'Tripura'), ('OD', 'Odisha'), ('HP', 'Haryana'), ('AR', 'Arunachal Pradesh'), ('ML', 'Meghalaya'), ('TN', 'Tamil Nadu'), ('CG', 'Chhattisgarh'), ('NL', 'Nagaland'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('BR', 'Bihar'), ('MN', 'Manipur'), ('ND', 'New Delhi'), ('MZ', 'Mizoram'), ('KL', 'Kerala'), ('WB', 'West Bengal'), ('RJ', 'Rajasthan'), ('JH', 'Jharkhand'), ('TS', 'Telegana'), ('MI', 'Sikkim'), ('KA', 'Karnataka'), ('UP', 'Uttar Pradesh'), ('AP', 'Andhra Pradesh'), ('GJ', 'Gujarat'), ('PB', 'Punjab'), ('UK', 'Uttarakhand'), ('AS', 'Assam')], max_length=100),
        ),
    ]
