# Generated by Django 2.0 on 2021-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210318_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Cars', 'Cars'), ('Laptops', 'Laptops'), ('Jobs', 'Jobs'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion'), ('Bikes', 'Bikes'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('KL', 'Kerala'), ('MH', 'Maharashtra'), ('TN', 'Tamil Nadu'), ('UK', 'Uttarakhand'), ('KA', 'Karnataka'), ('GA', 'Goa'), ('AP', 'Andhra Pradesh'), ('AS', 'Assam'), ('JH', 'Jharkhand'), ('GJ', 'Gujarat'), ('NL', 'Nagaland'), ('MZ', 'Mizoram'), ('OD', 'Odisha'), ('MI', 'Sikkim'), ('UP', 'Uttar Pradesh'), ('RJ', 'Rajasthan'), ('BR', 'Bihar'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('ND', 'New Delhi'), ('CG', 'Chhattisgarh'), ('WB', 'West Bengal'), ('AR', 'Arunachal Pradesh'), ('TR', 'Tripura'), ('HP', 'Haryana'), ('TS', 'Telegana'), ('MP', 'Madhya Pradesh'), ('PB', 'Punjab')], max_length=100),
        ),
    ]
