# Generated by Django 2.0 on 2021-03-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210318_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Furniture', 'Furniture'), ('Books&Sports', 'Books&Sports'), ('Cars', 'Cars'), ('Fashion', 'Fashion'), ('Laptops', 'Laptops'), ('Mobiles', 'Mobiles'), ('Electronics', 'Electronics'), ('Property', 'Property'), ('Bikes', 'Bikes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('KA', 'Karnataka'), ('MP', 'Madhya Pradesh'), ('GJ', 'Gujarat'), ('ML', 'Meghalaya'), ('TS', 'Telegana'), ('AS', 'Assam'), ('MZ', 'Mizoram'), ('JH', 'Jharkhand'), ('PB', 'Punjab'), ('HP', 'Haryana'), ('RJ', 'Rajasthan'), ('UP', 'Uttar Pradesh'), ('ND', 'New Delhi'), ('OD', 'Odisha'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('BR', 'Bihar'), ('AP', 'Andhra Pradesh'), ('MN', 'Manipur'), ('NL', 'Nagaland'), ('KL', 'Kerala'), ('GA', 'Goa'), ('AR', 'Arunachal Pradesh'), ('WB', 'West Bengal'), ('CG', 'Chhattisgarh'), ('TR', 'Tripura'), ('UK', 'Uttarakhand'), ('MI', 'Sikkim')], max_length=100),
        ),
    ]
