# Generated by Django 2.0 on 2021-03-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210318_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Jobs', 'Jobs'), ('Fashion', 'Fashion'), ('Books&Sports', 'Books&Sports'), ('Property', 'Property'), ('Electronics', 'Electronics'), ('Laptops', 'Laptops'), ('Mobiles', 'Mobiles'), ('Cars', 'Cars'), ('Bikes', 'Bikes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('WB', 'West Bengal'), ('TS', 'Telegana'), ('RJ', 'Rajasthan'), ('TR', 'Tripura'), ('GA', 'Goa'), ('AP', 'Andhra Pradesh'), ('TN', 'Tamil Nadu'), ('OD', 'Odisha'), ('ND', 'New Delhi'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('NL', 'Nagaland'), ('KL', 'Kerala'), ('MZ', 'Mizoram'), ('MH', 'Maharashtra'), ('GJ', 'Gujarat'), ('HP', 'Haryana'), ('KA', 'Karnataka'), ('MP', 'Madhya Pradesh'), ('BR', 'Bihar'), ('ML', 'Meghalaya'), ('JH', 'Jharkhand'), ('PB', 'Punjab'), ('MN', 'Manipur'), ('AS', 'Assam'), ('MI', 'Sikkim'), ('CG', 'Chhattisgarh'), ('AR', 'Arunachal Pradesh')], max_length=100),
        ),
    ]
