# Generated by Django 3.1.7 on 2021-03-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210318_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Property', 'Property'), ('Laptops', 'Laptops'), ('Books&Sports', 'Books&Sports'), ('Electronics', 'Electronics'), ('Cars', 'Cars'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('CG', 'Chhattisgarh'), ('MH', 'Maharashtra'), ('KL', 'Kerala'), ('OD', 'Odisha'), ('AR', 'Arunachal Pradesh'), ('GJ', 'Gujarat'), ('UK', 'Uttarakhand'), ('ML', 'Meghalaya'), ('TN', 'Tamil Nadu'), ('TS', 'Telegana'), ('UP', 'Uttar Pradesh'), ('BR', 'Bihar'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('GA', 'Goa'), ('MP', 'Madhya Pradesh'), ('NL', 'Nagaland'), ('AS', 'Assam'), ('MZ', 'Mizoram'), ('MI', 'Sikkim'), ('HP', 'Haryana'), ('MN', 'Manipur'), ('TR', 'Tripura'), ('PB', 'Punjab'), ('ND', 'New Delhi'), ('WB', 'West Bengal'), ('RJ', 'Rajasthan'), ('AP', 'Andhra Pradesh')], max_length=100),
        ),
    ]
